name: Deploy to Hostinger

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          port: 22
          script: |
            cd public_html/project
            git pull origin main
            # If Node/React project
            npm install
            npm run build
            rm -rf ../academic.vpszeta.in/*
            cp -r build/* ../academic.vpszeta.in/
