name: Deploy Vite React App to Hostinger via FTP

on:
  workflow_dispatch:

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build Vite React App
      run: npm run build

    - name: Install lftp
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: Deploy via lftp
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: trigmauser
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        lftp -e "set ssl:verify-certificate no; mirror -R ./dist /public_html --delete --verbose; quit" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST
