name: Deploy Vite React App to Hostinger

on:
  workflow_dispatch:    # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'   # Recommended Node version

    - name: Install dependencies
      run: npm install

    - name: Build Vite React App
      run: npm run build

    - name: Deploy to Hostinger via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          rm -rf /home/${{ secrets.SSH_USERNAME }}/public_html/*
          cp -r ./dist/* /home/${{ secrets.SSH_USERNAME }}/public_html/
