name: Deploy React + Vite to Hostinger

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build React project
        run: npm run build

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: 46.28.45.69
          username: u826569384
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          port: 65002
          script: |
            rm -rf /home/u826569384/public_html/academic.vpszeta.in/*
            cp -r ./dist/* /home/u826569384/public_html/academic.vpszeta.in/
